FROM python:3.10

RUN apt-get update && apt-get install -y --no-install-recommends postgresql-client && rm -rf /var/cache/apt/archives /var/lib/apt/lists/*

RUN curl -L https://github.com/golang-migrate/migrate/releases/latest/download/migrate.linux-amd64.tar.gz -o migrate.tar.gz && \
    tar -xvzf migrate.tar.gz -C /usr/local/bin migrate && \
    chmod +x /usr/local/bin/migrate && \
    rm migrate.tar.gz

COPY requirements.txt . 
RUN pip install -r requirements.txt
